version: '3.8'

services:
  db:
    container_name: db
    build: db/.
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

  user_service:
    container_name: user_service
    build: user_service/.
    depends_on:
      - db
    restart: on-failure
    environment:
      - TZ=Asia/Bangkok

  pet_service:
    container_name: pet_service
    build: pet_service/.
    depends_on:
      - db
    restart: on-failure
    environment:
      - TZ=Asia/Bangkok

  reminder_service:
    container_name: reminder_service
    build: reminder_service/.
    depends_on:
      - db
    restart: on-failure
    environment:
      - TZ=Asia/Bangkok

  notification_service:
    container_name: notification_service
    build: notification_service/.
    depends_on:
      - db
    restart: on-failure
    environment:
      - TZ=Asia/Bangkok

  cronjob:
    container_name: cronjob
    build: cronjob/.
    depends_on:
      - db
    restart: on-failure
    environment:
      - TZ=Asia/Bangkok
  
  file_storage_service:
    container_name: file_storage_service
    build: file_storage_service/.
    depends_on:
      - db
    restart: on-failure
    environment:
      - TZ=Asia/Bangkok

  document_service:
    container_name: document_service
    build: document_service/.
    depends_on:
      - es
    restart: on-failure
    environment:
      - TZ=Asia/Bangkok

  drug_label_extraction_service:
    container_name: drug_label_extraction_service
    build: drug_label_extraction_service/.
    depends_on:
      - user_service
    restart: on-failure
    environment:
      - TZ=Asia/Bangkok

  liff_app_gateway:
    container_name: liff_app_gateway
    build: liff_app_gateway/.
    ports:
      - "8080:80"
    depends_on:
      - user_service
      - pet_service
      - reminder_service
      - file_storage_service
    restart: on-failure
  
  es:
    build: elasticsearch/.
    ports:
      - "9200:9200"
    volumes:
      - es-data:/usr/share/elasticsearch/data

volumes:
  es-data:

  db-data:
    driver: local