version: '3.8'

name: senior_project

services:
  image_info_db:
    image: mysql:8.2
    container_name: image_info_db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=image_info_db
    ports:
      - "3306:3306"
    networks:
      - senior_project_network
    volumes:
      - .docker/setup.sql:/docker-entrypoint-initdb.d/setup.sql
      - image_info_db-data:/var/lib/mysql
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.3
    container_name: es
    environment: ['ES_JAVA_OPTS=-Xms2g -Xmx2g','bootstrap.memory_lock=true','discovery.type=single-node','xpack.security.enabled=false', 'xpack.security.enrollment.enabled=false']
    ports:
      - "9200:9200"
    networks:
      - senior_project_network
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    deploy:
      resources:
        limits:
          cpus: '2.0'
        reservations:
          cpus: '1.0'
    volumes:
      - es-data:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.3
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://es:9200
    ports:
      - "5601:5601"
    networks:
      - senior_project_network
    deploy:
      resources:
        limits:
          cpus: '2.0'
        reservations:
          cpus: '1.0'

  admin_management_service:
    build:
      context: ./admin_management_service
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    networks:
      - senior_project_network

  drug_label_extraction_service:
    build:
      context: ./drug_label_extraction_service/app
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    networks:
      - senior_project_network

networks:
  senior_project_network:

volumes:
  es-data:
  image_info_db-data:
    driver: local