version: '3.8'

services:  
  # es:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
  #   container_name: es
  #   environment: ['ES_JAVA_OPTS=-Xms2g -Xmx2g','bootstrap.memory_lock=true','discovery.type=single-node','xpack.security.enabled=false', 'xpack.security.enrollment.enabled=false']
  #   ports:
  #     - "9200:9200"
  #   ulimits:
  #     memlock:
  #       soft: -1
  #       hard: -1
  #     nofile:
  #       soft: 65536
  #       hard: 65536
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: '2.0'
  #       reservations:
  #         cpus: '1.0'
  #   volumes:
  #     - es-data:/usr/share/elasticsearch/data
  es:
    build: elasticsearch/.
    ports:
      - "9200:9200"
    volumes:
      - es-data:/usr/share/elasticsearch/data
  
  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.0
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://es:9200
    ports:
      - "5601:5601"
    depends_on:
      - es

volumes:
  es-data:
  
  db-data:
    driver: local