version: '3.8'
services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    container_name: es
    environment: ['ES_JAVA_OPTS=-Xms2g -Xmx2g','bootstrap.memory_lock=true','discovery.type=single-node','xpack.security.enabled=false', 'xpack.security.enrollment.enabled=false']
    ports:
      - "9200:9200"
    networks:
      - senior_project_network
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    deploy:
      resources:
        limits:
          cpus: '2.0'
        reservations:
          cpus: '1.0'
    volumes:
      - ./init_script.sh:/usr/share/elasticsearch/config/init_script.sh
      - es-data:/usr/share/elasticsearch/data
    command: /bin/bash -c "/usr/share/elasticsearch/config/init_script.sh"

  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.3
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://es:9200
    ports:
      - "5601:5601"
    networks:
      - senior_project_network
    deploy:
      resources:
        limits:
          cpus: '2.0'
        reservations:
          cpus: '1.0'

  document_service:
    container_name: document_service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - senior_project_network

networks:
  senior_project_network:

volumes:
  es-data: